export { default as Header } from './header'
export { default as Loading } from './loading'
export { default as Modal } from './modal'
export { default as Movie } from './movie'
export { default as MovieList } from './movieList'
export { default as Tab } from './tab'
